import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightbulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 max-md:pt-16 max-sm:pt-8">
          <div className="flex items-center justify-between w-full max-lg:flex-col">
            <div className="w-1/2 max-md:w-full">
              <Image
                src={profilePic}
                alt="Manas Suple"
                className="w-full h-auto max-lg:hidden max-md:inline-block max-md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center max-lg:w-full max-lg:text-center">
              <AnimatedText
                text="Always ready to explore, experiment, and create."
                className="!text-6xl !text-left max-xl:!text-5xl max-lg:!text-center max-lg:text-6xl max-md:!text-5xl max-sm:!text-3xl"
              />

              <p className="my-4 text-base font-medium max-md:text-sm max-sm:text-xs">
                As a developer, I love to turn ideas into experiences through my
                innovative web and mobile applications. Explore my projects and
                certifications, showcasing my expertise in various languages and
                frameworks
              </p>
              <div className="flex items-center self-start mt-2 max-lg:self-center">
                <Link
                  href="/Resume-new.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg  font-semibold
                   hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                    dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                    max-md:p-2 max-md:px-4 max-md:text-base
                    "
                  download={true}
                >
                  Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <a
                  href="https://mail.google.com/mail/?view=cm&to=manassuple163@gmail.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light max-md:text-base"
                >
                  Contact
                </a>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 max-md:hidden">
          <Image src={lightbulb} alt="Manas Suple" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
